theme = "ayu_mirage"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
enable = true
display-messages = true

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" 

editor.whitespace.render = "all"
editor.indent-guides.render = true

[keys.normal]
space.q = ":q"
space.w = ":w"
